Upgraded the Meta XR SDK to v67. TODO: Merge this into master after the next version of 3D WebView after v4.8 (either v4.8.1 or v4.9) is released. This next release will include an update to fix the following compiler error that occurs with Meta XR SDK v67: "error CS0117: 'OVRProjectConfig' does not contain a definition for 'GetProjectConfig'".